"""empty message

Revision ID: dea1ea803254
Revises: 4cb1d5b2b489
Create Date: 2025-09-12 17:15:11.277842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'dea1ea803254'
down_revision = '4cb1d5b2b489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True, server_default='UTC'))
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True, server_default='en'))
        # Skip altering created_at - it already exists and works fine
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        # Skip foreign key creation if roles table doesn't exist yet
        # batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               existing_nullable=False,
               existing_server_default=sa.text('(getutcdate())'))
        batch_op.drop_column('language')
        batch_op.drop_column('timezone')
        batch_op.drop_column('phone')
        batch_op.drop_column('department')
        batch_op.drop_column('last_login')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('is_locked')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
